language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script:
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --dev

script: phpunit  --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
